language: ruby
node_js:
    - "8.10"
rvm: 
    - 2.5.1
install:
    - gem install jekyll bundler
before_script:
    - bundle install
script:
    - bundle exec jekyll build
branches:
    only:
        - release
        - Develop
        - master
after_success:
    - echo "Build was successful"

deploy:
    provider: pages
    skip_cleanup: true
    github_token: 31aad84e551c16f7f83cf94ed5f28f6625173219
    on:
        branch: master