language: ruby
services:
    -docker

script:
    - docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll:3.8 /bin/bash -c "chmod a+wx . && jekyll build"
    - if[[${TRAVIS_BRANCH} == "master"]]; then  bundle exec jekyll algolia; fi
branches:
    only:
        - gh-pages
        - Develop
        - master
after_success:
    - echo "Build was successful"

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branches:
          only:
            - gh-pages
# deploy:
#   provider: script
#   script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push gathuku/zege_fidget
#   on:
#     branch: master
